[package]
name = "bupt-report-template"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Yokumi"]
license = "MIT"
description = "北京邮电大学课程作业报告 Typst 模板。Beijing University of Posts and Telecommunications Course Report Typst Template."
repository = "https://github.com/Yokumii/BUPT-Report-Template-by-Typst"
keywords = ["Beijing University of Posts and Telecommunications", "BUPT", "report", "course"]
categories = ["report"]
exclude = []

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
